### PR TITLE
FIX: Use filter style instead of attr

### PR DESCRIPTION
**Pull request by chapel**
Fix for #10 which is still a problem with latest Firefox.

### CODE REVIEW

**Comment by SamSaffron** [comment]
Have you tried this on IE / FF / Chrome ?

**Comment by chapel** [comment]
Not supported in IE: https://developer.mozilla.org/en-US/docs/Web/CSS/filter#Browser_compatibility

Tested the change manually in FF and Chrome, but not this PR specifically since I don't have a local dev environment setup for Discourse.

**Comment by chapel** [comment]
Actually, looks like the original syntax was for IE compatibility. I don't have IE handy, but honestly it should work if we were to have both the style and attribute logic if IE is the reason for the attribute. I'll have to look into this tomorrow or later though.

**Comment by chapel** [comment]
@SamSaffron, tested the modified version in Chrome and FF, but again no IE.

**Comment by SamSaffron** [comment]
Well here goes nothing :) 

thanks for the patch!

**Comment by chapel** [comment]
Hmm, Firefox is really messed up. It works when applying it at runtime, but doesn't fix the issue when on first load, but sometimes it does... I'll take a look and fix this once and for all, it may require a FF or IE specific patch to how it is handled since it seems the way IE needs it is also breaking FF, but it could be deeper and specific to how FF is trying to load the url filter.

**Pull request merged**
